### ISSUE TITLE
Nginx OPTIONS 请求 405 错误

### ISSUE THREAD

**Issue by Dream4ever** [Dream4ever/Knowledge-Base#126]
## 问题描述

业务部署到 CentOS 服务器上之后，没有做全面的测试。最近查看 Nginx 日志，发现其中一项业务的某个 API 一直报 405 错误，上网搜索了一下，需要配置 Nginx 来解决这个问题。

## 解决流程

- 关键词：`nginx options 405`
- 解决方案：[Handling OPTIONS request in nginx](https://stackoverflow.com/questions/227939)

关键代码：

```
location / {
    if ($request_method = OPTIONS ) {
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 200;
    }
}
```

**Comment by chanlyang** [comment]
location /  会过滤所有的options请求吗？

**Comment by Dream4ever** [comment]
> location / 会过滤所有的options请求吗？

如果只有这一条规则的话，应该是可以的吧，你可以自己本地找个环境测试一下看看。
