### ISSUE TITLE
ExcelJS 在前端浏览器中读取 Excel 文件内容

### ISSUE THREAD

**Issue by Dream4ever** [Dream4ever/Knowledge-Base#142]
## 需求描述

如题

## 解决过程

Google 关键字 `exceljs parse xlsx browser`，第一个链接 [how to read xlsx file in browser with exceljs? · Issue #832](https://github.com/exceljs/exceljs/issues/832) 中就有具体的代码。

```js
handleChange(e) {
  this.file = e.target.files[0]
},
handleImport() {
  const wb = new Excel.Workbook();
  const reader = new FileReader()

  reader.readAsArrayBuffer(this.file)
  reader.onload = () => {
    const buffer = reader.result;
    wb.xlsx.load(buffer).then(workbook => {
      console.log(workbook, 'workbook instance')
      workbook.eachSheet((sheet, id) => {
        sheet.eachRow((row, rowIndex) => {
          console.log(row.values, rowIndex)
        })
      })
    })
  }
}
```

**Comment by chandanrjit2021** [comment]
![image](https://user-images.githubusercontent.com/85793080/134138606-b3a4567f-44c2-4e47-89c1-3d2c2d97f03c.png)

@Dream4ever  Can you please help with the above error

**Comment by Dream4ever** [comment]
> ![image](https://user-images.githubusercontent.com/85793080/134138606-b3a4567f-44c2-4e47-89c1-3d2c2d97f03c.png)
> 
> @Dream4ever Can you please help with the above error

Try this:

```js
readFile (file) {
  return new Promise((resolve, reject) => {
    var fr = new FileReader()
    fr.onload = () => {
      resolve(fr.result)
    }
    fr.onerror = reject
    fr.readAsArrayBuffer(file)
  })
},
```
